### ISSUE TITLE
ReentrancyGuard state is not properly initialized

### ISSUE THREAD

**Issue by mgcolburn** [dforce-network/dToken#19]
Severity: Informational

### Description
`ReentrancyGuard` was updated to reflect a newer version of OpenZeppelin, which moves from `bool notStarted` to this:

```
    uint256 private constant _NOT_ENTERED = 1;
    uint256 private constant _ENTERED = 2;

    uint256 private _status;

    constructor() internal {
        _status = _NOT_ENTERED;
    }

```

However, `_status` is no longer being set in the `initialize` function anymore.

```
modifier nonReentrant() {
        // On the first call to nonReentrant, _notEntered will be true
        require(_status != _ENTERED, "ReentrancyGuard: reentrant call");
```

### Recommendation
Properly initialize the `ReentrancyGuard` as well when initializing the contracts.

**Comment by Donald-Nobel** [comment]
Will fix it like this,
add internal function initializeStatus() {  _status = _NOT_ENTERED; } in ReentrancyGuard.sol, call it in initialize function who inherit ReentrancyGuard.
