### ISSUE TITLE
DToken is not ERC20-compliant

### ISSUE THREAD

**Issue by mgcolburn** [dforce-network/dToken#20]
Severity: Informational

### Description
According to [the EIP-20 standard](https://eips.ethereum.org/EIPS/eip-20), if implemented, the `decimals` function should return a `uint8`. However, as the `decimals` state variable in the `DToken` contract is declared as a `uint256`, the auto-generated getter function will return a `uint256` instead of the expected type.

### Recommendation
Correct the type of the `decimals` variable to a `uint8`.

**Comment by Donald-Nobel** [comment]
Will fix it.

**Comment by bamboo-seven** [comment]
Fixed in 792bb333a1770e8da6a67c3730246f920049153e
