### ISSUE TITLE
The selector attribute should be used instead of hardcoding the selector

### ISSUE THREAD

**Issue by mgcolburn** [dforce-network/dToken#30]
Severity: Code Quality

### Description
Origination fees are calculated based on the function call that triggers it. However, `redeem()` is intended to share the same fee as calls to `burn()`. This function identifier is hardcore into the contract:
` _redeemLocal.originationFee = originationFee[0x9dc29fac];`

The use of magic numbers such as this should be avoided and this constant could be replaced by `DToken(this).burn.selector` for improved clarity.

**Comment by Donald-Nobel** [comment]
New stuff, will do it.
